#!/bin/bash
psql -h localhost -U postgres -c "COPY (SELECT string_agg(format('DROP DATABASE %I;', datname), '') FROM pg_database WHERE datistemplate = false AND datname LIKE 'test_%') TO '/tmp/database_to_remove.sql'";
psql -h localhost -U postgres -f /tmp/database_to_remove.sql;
