#!/bin/bash
psql -h localhost -U postgres -c "COPY (SELECT string_agg(format('DROP DATABASE %I;', datname), '') FROM pg_database WHERE datistemplate = FALSE AND datname LIKE 'test_%' AND (pg_stat_file(format('base/%s/PG_VERSION', oid))).modification + INTERVAL '2 MINUTES' < now()) TO '/tmp/database_to_remove.sql'";
psql -h localhost -U postgres -f /tmp/database_to_remove.sql;
