sudo: required

services:
  - postgresql
  - redis-server

addons:
  postgresql: 9.6

language: php

php:
  - 7.2
  - nightly

before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-10 postgresql-client-10
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - export PGPORT=5433
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

before_script:
  - cp -f Tests/Configuration/.config.travis.ini Tests/Configuration/.config.local.ini
  - cp -f App/Configuration/.config.travis.ini App/Configuration/.config.local.ini
  - sudo cp -f ./docker/php-fpm/sendmail /usr/sbin/fake-sendmail && sudo chmod +x /usr/sbin/fake-sendmail
  - psql -c 'CREATE DATABASE find_my_friends_test;' -U postgres
  - psql -U postgres find_my_friends_test < fixtures/schema.sql
  - wget https://raw.githubusercontent.com/klapuch/plpgunit/master/install/1.install-unit-test.sql -O Tests/fixtures/plpgunit.sql
  - psql -U postgres find_my_friends_test < Tests/fixtures/plpgunit.sql
  - psql -U postgres find_my_friends_test < Tests/fixtures/test_utils.sql
  - psql -U postgres find_my_friends_test < Tests/fixtures/samples.sql
  - for file in fixtures/dumps/*.sql; do psql -U postgres find_my_friends_test < $file; done;

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then vendor/bin/phing ci; else vendor/bin/phing; fi # Code coverage test

after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then php coveralls.phar --verbose --config Tests/.coveralls.yml; fi

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
