version: '3'
networks:
  fmf:
    external: true

volumes:
  fmf-postgres:
    external: true

services:
    postgres:
      container_name: find-my-friends-postgres
      build: docker/postgres
      env_file: ./docker/.env.local
      volumes:
        - fmf-postgres:/var/lib/postgresql/data
        - ./docker/postgres/postgresql.conf:/etc/postgresql.conf
        - ./:/var/www/FindMyFriends
      command: postgres -c config_file=/etc/postgresql.conf
      ports:
        - 5433:5432
      networks:
        - fmf

    php-fpm:
      build: docker/php-fpm
      working_dir: /var/www/FindMyFriends
      volumes:
          - ./:/var/www/FindMyFriends
          - ./docker/php-fpm/sendmail:/usr/sbin/fake-sendmail
          - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      networks:
        - fmf

    nginx:
      image: nginx:alpine
      container_name: find-my-friends-nginx
      volumes:
          - ./:/var/www/FindMyFriends:ro
          - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      networks:
        - fmf

    redis:
      image: redis:alpine
      container_name: find-my-friends-redis
      ports:
        - 6379:6379
      networks:
        - fmf

    redis-test:
      build: docker/redis-test
      container_name: find-my-friends-redis-test
      ports:
        - 6380:6380
      networks:
        - fmf