version: '3'
networks:
  fmf:
    external: true

volumes:
  fmf-postgres:
    external: true

services:
    postgres:
      container_name: find-my-friends-postgres
      build: docker/postgres
      env_file: ./docker/.env.local
      volumes:
        - ./:/var/www/FindMyFriends
        - fmf-postgres:/var/lib/postgresql/data
      command: postgres -c config_file=/etc/postgresql.conf
      ports:
        - 5433:5432
      networks:
        - fmf

    php-fpm:
      build: docker/php-fpm
      working_dir: /var/www/FindMyFriends
      volumes:
          - ./:/var/www/FindMyFriends
      networks:
        - fmf

    nginx:
      build: docker/nginx
      container_name: find-my-friends-nginx
      volumes:
          - ./:/var/www/FindMyFriends:ro
      ports:
        - 80:80
        - 443:443
      networks:
        - fmf

    redis:
      image: redis:alpine
      container_name: find-my-friends-redis
      networks:
        - fmf

    redis-identity:
      image: redis:alpine
      container_name: find-my-friends-redis-identity
      networks:
        - fmf

    redis-test:
      image: redis:alpine
      container_name: find-my-friends-redis-test
      networks:
        - fmf

    kibana:
      image: kibana
      container_name: find-my-friends-kibana
      ports:
        - 5601:5601
      networks:
        - fmf

    elasticsearch:
      image: elasticsearch
      container_name: find-my-friends-elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      networks:
        - fmf

    rabbitmq:
      image: rabbitmq:management
      container_name: find-my-friends-rabbitmq
      ports:
        - 15672:15672
        - 5672:5672
      networks:
        - fmf
